spring:
  kafka:
    #địa chỉ kafka broker
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:default-group}

  mail:
    host: smtp.gmail.com
    port: 587
    username: binhltse173315@fpt.edu.vn
    password: bdbv kkrx zead dwxj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp